name: Build and deploy Python Function App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: fa-uel-incident-scorer
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # IMPORTANT: install into .python_packages so Azure can import at runtime
      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      # (optional) verify that joblib is present
      - name: List installed top-level packages
        run: |
          ls -1 .python_packages/lib/site-packages | head -n 50

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.APP_NAME }}
          package: .
